### PR TITLE
Batch import secret keys to avoid interactive prompt with GnuPG 2.1+

### PR DESCRIPTION
**Pull request by mattock**
GnuPG 2.1 and later prompts for secret key passphrase if --import is not coupled with --batch. The rationale for the changed behavior is described in https://dev.gnupg.org/T2313. This problem affects at least Debian 9 ("stretch") which is bundled with GnuPG 2.1.18.

With this change all --import calls include --batch, so that private keys get imported without user interaction. This did not seem to have any ill effects on older GnuPG versions, such as 1.4.18, which comes in Debian 7 ("wheezy").

### CODE REVIEW

**Comment by mattock** [comment]
@dgolja It's not obvious how the Travis CI [build error](https://travis-ci.org/dgolja/golja-gnupg/jobs/226793759#L207-L219) is related to my PR, if it is at all. Any pointers?

**Comment by karn09** [comment]
Just came across this issue. This helped me solve it. Thanks!

**Comment by mattock** [comment]
@karn09 no problem!

**Comment by DLeich** [comment]
I just ran into this issue on Oracle Linux 8.  Unfortunately, considering there hasn't been an updated release since 2016, that makes me think that this module has unfortunately fizzled out.  Unless this PR gets merged, that means this module will not support modern OS versions which include GnuPG 2.1+.

**Comment by DLeich** [comment]
@dgolja - What's the status of this module?  Seems like maybe you need a little help maintaining it?

**Comment by mattock** [comment]
I think this module is unmaintained. @DLeich maybe we should just fork this to get changes merged in one place.

**Comment by dgolja** [comment]
sorry it's almost unmaintaned. Happy to merge this PR and happy to add elevated privileges to help maintain this module.

**Comment by DLeich** [comment]
@dgolja - Would you be perhaps interested in migrating your module to Vox Pupuli?  That would probably really help with sharing maintenance of the code.  See https://voxpupuli.org/docs/migrate_module/ on the procedures to get it migrated.

**Pull request merged**
